'use client';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';

const features = [
  { icon: '🧠', title: 'AI-Powered Plans', desc: 'Personalized meal plans generated by intelligent nutrition algorithms tailored to your body.', color: 'cyan' },
  { icon: '📊', title: 'BMR & TDEE Calc', desc: 'Precise Mifflin-St Jeor formula calculations for your basal metabolic rate and total daily energy.', color: 'green' },
  { icon: '🥩', title: 'Macro Tracking', desc: 'Optimal protein, carbs & fat distribution based on your specific fitness goal.', color: 'purple' },
  { icon: '📅', title: 'Weekly Meal Plans', desc: '7-day structured meal plans with Indian & international foods, tailored to dietary preferences.', color: 'orange' },
  { icon: '📈', title: 'Progress Dashboard', desc: 'Interactive charts for weight trends, macro progress, and goal completion analytics.', color: 'pink' },
  { icon: '🍽️', title: 'Food Database', desc: 'Log daily meals with 50+ foods (calories, protein, carbs, fat) and track against daily targets.', color: 'gold' },
];

const goals = [
  { label: 'Fat Loss', emoji: '🔥', desc: '−500 kcal deficit', color: 'from-orange-500 to-red-500' },
  { label: 'Muscle Gain', emoji: '💪', desc: '+300 kcal surplus', color: 'from-cyan-500 to-blue-500' },
  { label: 'Lean Body', emoji: '⚡', desc: 'Body recomp', color: 'from-purple-500 to-pink-500' },
  { label: 'Maintenance', emoji: '⚖️', desc: 'TDEE matched', color: 'from-green-500 to-teal-500' },
];

const stats = [
  { value: '50K+', label: 'Active Users' },
  { value: '2.4M', label: 'Meals Planned' },
  { value: '98%', label: 'Goal Success' },
  { value: '4.9★', label: 'User Rating' },
];

export default function LandingPage() {
  const { user, loading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!loading && user) router.push('/dashboard');
  }, [user, loading, router]);

  return (
    <main style={{ minHeight: '100vh' }}>
      {/* ─── Navbar ─────────────────────────────────────────── */}
      <nav style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 50,
        padding: '16px clamp(16px, 4vw, 40px)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: 'rgba(5, 8, 20, 0.8)',
        backdropFilter: 'blur(20px)',
        borderBottom: '1px solid rgba(255,255,255,0.06)',
      }}>
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}
          style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{
            width: 40, height: 40, borderRadius: 12,
            background: 'linear-gradient(135deg, #00d4ff, #00ff87)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 20, fontWeight: 900
          }}>Q</div>
          <span style={{ fontSize: '1.25rem', fontWeight: 800, letterSpacing: '-0.02em' }}>
            Qevi<span className="gradient-text">Diet</span>
          </span>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
          style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <Link href="/login" style={{
            padding: '8px 20px', borderRadius: 10,
            border: '1px solid rgba(255,255,255,0.1)',
            background: 'rgba(255,255,255,0.04)',
            color: '#f0f4ff', fontWeight: 500, fontSize: '0.9rem',
            textDecoration: 'none', transition: 'all 0.2s',
          }}>Sign In</Link>
          <Link href="/register">
            <button className="btn-primary" style={{ padding: '8px 22px', borderRadius: 10, fontSize: '0.9rem' }}>
              <span>Get Started Free</span>
            </button>
          </Link>
        </motion.div>
      </nav>

      {/* ─── Hero ────────────────────────────────────────────── */}
      <section style={{ paddingTop: '160px', paddingBottom: '100px', textAlign: 'center', padding: '160px 24px 100px' }}>
        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
          <div className="badge badge-cyan" style={{ display: 'inline-flex', marginBottom: 24 }}>
            ✨ AI-Powered Nutrition Intelligence
          </div>

          <h1 style={{
            fontSize: 'clamp(2.5rem, 6vw, 5rem)',
            fontWeight: 900,
            lineHeight: 1.1,
            letterSpacing: '-0.03em',
            marginBottom: 24,
            maxWidth: 900,
            margin: '0 auto 24px',
          }}>
            Your Body Deserves a<br />
            <span className="gradient-text">Smarter Diet Plan</span>
          </h1>

          <p style={{
            fontSize: 'clamp(1rem, 2vw, 1.25rem)',
            color: 'var(--text-muted)',
            maxWidth: 600,
            margin: '0 auto 48px',
            lineHeight: 1.7,
          }}>
            Get a personalized weekly meal plan calculated from your BMR, TDEE & fitness goal.
            Track macros, log meals, and crush your physique goals with AI precision.
          </p>

          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/register">
              <motion.button
                className="btn-primary"
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                style={{ padding: '16px 36px', fontSize: '1.05rem', borderRadius: 14 }}
              >
                <span>🚀 Start Your Free Plan</span>
              </motion.button>
            </Link>
            <Link href="/login">
              <motion.button
                className="btn-secondary"
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                style={{ padding: '16px 36px', fontSize: '1.05rem' }}
              >
                View Demo Dashboard
              </motion.button>
            </Link>
          </div>
        </motion.div>

        {/* Stats Bar */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4, duration: 0.7 }}
          style={{
            display: 'flex', justifyContent: 'center', gap: 'clamp(20px, 5vw, 48px)', flexWrap: 'wrap',
            marginTop: 72,
            padding: '32px 40px',
            background: 'rgba(255,255,255,0.03)',
            borderRadius: 24,
            border: '1px solid rgba(255,255,255,0.06)',
            backdropFilter: 'blur(20px)',
            maxWidth: 800,
            marginLeft: 'auto',
            marginRight: 'auto',
          }}
        >
          {stats.map((s) => (
            <div key={s.label} style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '2rem', fontWeight: 900, marginBottom: 4 }} className="gradient-text">{s.value}</div>
              <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 500 }}>{s.label}</div>
            </div>
          ))}
        </motion.div>
      </section>

      {/* ─── Goals Section ───────────────────────────────────── */}
      <section style={{ padding: '80px 24px', maxWidth: 1100, margin: '0 auto' }}>
        <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
          style={{ textAlign: 'center', marginBottom: 56 }}>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: 800, marginBottom: 16 }}>
            Choose Your <span className="gradient-text-purple">Fitness Goal</span>
          </h2>
          <p style={{ color: 'var(--text-muted)', maxWidth: 500, margin: '0 auto' }}>
            Our AI calibrates your entire diet plan around your specific goal automatically.
          </p>
        </motion.div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 20 }}>
          {goals.map((g, i) => (
            <motion.div
              key={g.label}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              whileHover={{ y: -6, scale: 1.02 }}
              style={{
                background: `linear-gradient(135deg, rgba(255,255,255,0.04), rgba(255,255,255,0.01))`,
                border: '1px solid rgba(255,255,255,0.08)',
                borderRadius: 20,
                padding: '32px 24px',
                textAlign: 'center',
                cursor: 'pointer',
                position: 'relative',
                overflow: 'hidden',
              }}
            >
              <div style={{ fontSize: '2.5rem', marginBottom: 12 }}>{g.emoji}</div>
              <div style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: 8 }}>{g.label}</div>
              <div style={{
                display: 'inline-block', padding: '4px 12px', borderRadius: 999,
                background: `linear-gradient(135deg, ${g.color.split(' ')[1]}, ${g.color.split(' ')[3]})`,
                fontSize: '0.78rem', fontWeight: 600, color: '#fff', opacity: 0.9,
              }}>{g.desc}</div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ─── Features ────────────────────────────────────────── */}
      <section style={{ padding: '80px 24px', maxWidth: 1100, margin: '0 auto' }}>
        <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
          style={{ textAlign: 'center', marginBottom: 56 }}>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: 800, marginBottom: 16 }}>
            Everything You Need to <span className="gradient-text">Succeed</span>
          </h2>
        </motion.div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 24 }}>
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              className="glass-card"
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              style={{ padding: '28px' }}
            >
              <div style={{
                width: 52, height: 52, borderRadius: 14,
                background: f.color === 'cyan' ? 'rgba(0,212,255,0.15)' :
                  f.color === 'green' ? 'rgba(0,255,135,0.15)' :
                    f.color === 'purple' ? 'rgba(168,85,247,0.15)' :
                      f.color === 'orange' ? 'rgba(255,107,0,0.15)' :
                        f.color === 'pink' ? 'rgba(255,0,110,0.15)' : 'rgba(255,215,0,0.15)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: '1.6rem', marginBottom: 16,
              }}>{f.icon}</div>
              <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: 8 }}>{f.title}</h3>
              <p style={{ color: 'var(--text-muted)', lineHeight: 1.6, fontSize: '0.9rem' }}>{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ─── How It Works ────────────────────────────────────── */}
      <section style={{ padding: '80px 24px', maxWidth: 900, margin: '0 auto' }}>
        <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
          style={{ textAlign: 'center', marginBottom: 56 }}>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: 800, marginBottom: 16 }}>
            How <span className="gradient-text">QeviDiet</span> Works
          </h2>
        </motion.div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
          {[
            { step: '01', title: 'Create Your Profile', desc: 'Enter age, weight, height, body type, activity level and fitness goal. Takes 2 minutes.', icon: '👤' },
            { step: '02', title: 'AI Calculates Your Needs', desc: 'Mifflin-St Jeor BMR → TDEE with activity multiplier → Goal-adjusted calories → Optimal macros.', icon: '⚡' },
            { step: '03', title: 'Get Your Weekly Plan', desc: 'Receive a complete 7-day meal plan with breakfast, lunch, dinner & snacks tailored to you.', icon: '📋' },
            { step: '04', title: 'Track & Improve', desc: 'Log daily food intake, monitor weight trends, view progress charts and stay on target.', icon: '🎯' },
          ].map((item, i) => (
            <motion.div
              key={item.step}
              initial={{ opacity: 0, x: i % 2 === 0 ? -30 : 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.15 }}
              style={{
                display: 'flex', alignItems: 'flex-start', gap: 24,
                padding: '28px 0',
                borderBottom: i < 3 ? '1px solid rgba(255,255,255,0.05)' : 'none',
              }}
            >
              <div style={{
                width: 56, height: 56, borderRadius: 16, flexShrink: 0,
                background: 'linear-gradient(135deg, rgba(0,212,255,0.15), rgba(0,255,135,0.1))',
                border: '1px solid rgba(0,212,255,0.2)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: '1.6rem',
              }}>{item.icon}</div>
              <div>
                <div style={{ fontSize: '0.75rem', color: 'var(--neon-cyan)', fontWeight: 700, marginBottom: 6, letterSpacing: '0.1em' }}>STEP {item.step}</div>
                <div style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: 8 }}>{item.title}</div>
                <div style={{ color: 'var(--text-muted)', lineHeight: 1.6 }}>{item.desc}</div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ─── CTA ─────────────────────────────────────────────── */}
      <section style={{ padding: '80px 24px 120px', textAlign: 'center' }}>
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          style={{
            maxWidth: 700, margin: '0 auto',
            padding: 'clamp(36px, 6vw, 60px) clamp(20px, 5vw, 40px)',
            background: 'linear-gradient(135deg, rgba(0,212,255,0.08), rgba(0,255,135,0.05))',
            border: '1px solid rgba(0,212,255,0.2)',
            borderRadius: 32,
            backdropFilter: 'blur(20px)',
          }}
        >
          <div style={{ fontSize: '3rem', marginBottom: 16 }}>🚀</div>
          <h2 style={{ fontSize: 'clamp(1.6rem, 4vw, 2.5rem)', fontWeight: 800, marginBottom: 16 }}>
            Start Your Transformation Today
          </h2>
          <p style={{ color: 'var(--text-muted)', marginBottom: 36, lineHeight: 1.7, maxWidth: 500, margin: '0 auto 36px' }}>
            Join thousands who've transformed their physique with science-backed, AI-personalized nutrition. Free forever — no credit card needed.
          </p>
          <Link href="/register">
            <motion.button
              className="btn-primary"
              whileHover={{ scale: 1.04 }}
              whileTap={{ scale: 0.97 }}
              style={{ padding: '18px 48px', fontSize: '1.1rem', borderRadius: 16 }}
            >
              <span>🎯 Create Free Account</span>
            </motion.button>
          </Link>
        </motion.div>
      </section>

      {/* ─── Footer ──────────────────────────────────────────── */}
      <footer style={{
        borderTop: '1px solid rgba(255,255,255,0.06)',
        padding: '32px 24px',
        textAlign: 'center',
        color: 'var(--text-muted)',
        fontSize: '0.85rem',
      }}>
        <div style={{ marginBottom: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
          <div style={{
            width: 28, height: 28, borderRadius: 8,
            background: 'linear-gradient(135deg, #00d4ff, #00ff87)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 14, fontWeight: 900, color: '#050814',
          }}>Q</div>
          <span style={{ fontWeight: 700, color: '#f0f4ff' }}>QeviDiet</span>
        </div>
        <p>© 2026 QeviDiet. AI-Powered Nutrition Intelligence.</p>
      </footer>
    </main>
  );
}
